//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanTrack.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanTrack.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string BtnCloseText {
            get {
                return ResourceManager.GetString("BtnCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BtnDeleteText {
            get {
                return ResourceManager.GetString("BtnDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BtnSaveText {
            get {
                return ResourceManager.GetString("BtnSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit mode.
        /// </summary>
        internal static string BtnTextEditMode {
            get {
                return ResourceManager.GetString("BtnTextEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the section &lt;br /&gt;&lt;span class=&quot;text-danger&quot;&gt;{0}&lt;/span&gt;?
        ///This will also remove all of its contents..
        /// </summary>
        internal static string ConfirmModalDeleteSectionMessage {
            get {
                return ResourceManager.GetString("ConfirmModalDeleteSectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Section.
        /// </summary>
        internal static string ConfirmModalDeleteSectionTitle {
            get {
                return ResourceManager.GetString("ConfirmModalDeleteSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the section &lt;br /&gt; &lt;span class=&quot;text-danger&quot;&gt;{0}&lt;/span&gt;?
        ///.
        /// </summary>
        internal static string ConfirmModalDeleteTimerMessage {
            get {
                return ResourceManager.GetString("ConfirmModalDeleteTimerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Timer.
        /// </summary>
        internal static string ConfirmModalDeleteTimerTitle {
            get {
                return ResourceManager.GetString("ConfirmModalDeleteTimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your support!.
        /// </summary>
        internal static string DonationGratitudeMessage {
            get {
                return ResourceManager.GetString("DonationGratitudeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like the app and want to support its development, you can leave a small donation.
        /// </summary>
        internal static string DonationMessage {
            get {
                return ResourceManager.GetString("DonationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌍 International: Boosty (accepts cards) &lt;br /&gt;
        ///🇷🇺 Russia: Boosty / ЮMoney.
        /// </summary>
        internal static string DonationPaymentMethodsDescription {
            get {
                return ResourceManager.GetString("DonationPaymentMethodsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support CleanTrack.
        /// </summary>
        internal static string DonationTitle {
            get {
                return ResourceManager.GetString("DonationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Mode.
        /// </summary>
        internal static string EditMode {
            get {
                return ResourceManager.GetString("EditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Interval (min. 1).
        /// </summary>
        internal static string lblFieldDayInterval {
            get {
                return ResourceManager.GetString("lblFieldDayInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Done.
        /// </summary>
        internal static string lblFieldLastDateDone {
            get {
                return ResourceManager.GetString("lblFieldLastDateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name *.
        /// </summary>
        internal static string LblFieldName {
            get {
                return ResourceManager.GetString("LblFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days/hours/minutes ago.
        /// </summary>
        internal static string lblFieldTimeAgo {
            get {
                return ResourceManager.GetString("lblFieldTimeAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string LblSection {
            get {
                return ResourceManager.GetString("LblSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string LblTimer {
            get {
                return ResourceManager.GetString("LblTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timers in this section.
        /// </summary>
        internal static string msgProgressBarNaN {
            get {
                return ResourceManager.GetString("msgProgressBarNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your activities will appear here..
        /// </summary>
        internal static string NoItemFoundLine1 {
            get {
                return ResourceManager.GetString("NoItemFoundLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your first section or timer to get started..
        /// </summary>
        internal static string NoItemFoundLine2 {
            get {
                return ResourceManager.GetString("NoItemFoundLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string ShortcutSection {
            get {
                return ResourceManager.GetString("ShortcutSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string ShortcutTimer {
            get {
                return ResourceManager.GetString("ShortcutTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this app, you can create sections (like rooms, areas, or tasks) and add timers inside them, shown as progress bars..
        /// </summary>
        internal static string TutorialDescription1 {
            get {
                return ResourceManager.GetString("TutorialDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is organized in a clear tree structure, making it easy to track cleanliness and order..
        /// </summary>
        internal static string TutorialDescription2 {
            get {
                return ResourceManager.GetString("TutorialDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the name to show or hide actions.
        /// </summary>
        internal static string TutorialEditModeDescription {
            get {
                return ResourceManager.GetString("TutorialEditModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timer fills to 100% when updated, then decreases to 0% over the set number of days. If overdue, it drops to –100%..
        /// </summary>
        internal static string TutorialReadModeDescription {
            get {
                return ResourceManager.GetString("TutorialReadModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Mode.
        /// </summary>
        internal static string ViewMode {
            get {
                return ResourceManager.GetString("ViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👋 Welcome!.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
