//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanTrack.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanTrack.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit mode.
        /// </summary>
        internal static string BtnTextEditMode {
            get {
                return ResourceManager.GetString("BtnTextEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string LblSection {
            get {
                return ResourceManager.GetString("LblSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string LblTimer {
            get {
                return ResourceManager.GetString("LblTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your activities will appear here..
        /// </summary>
        internal static string NoItemFoundLine1 {
            get {
                return ResourceManager.GetString("NoItemFoundLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your first section or timer to get started..
        /// </summary>
        internal static string NoItemFoundLine2 {
            get {
                return ResourceManager.GetString("NoItemFoundLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this app, you can create sections (like rooms, areas, or tasks) and add timers inside them, shown as progress bars..
        /// </summary>
        internal static string TutorialDescription1 {
            get {
                return ResourceManager.GetString("TutorialDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is organized in a clear tree structure, making it easy to track cleanliness and order..
        /// </summary>
        internal static string TutorialDescription2 {
            get {
                return ResourceManager.GetString("TutorialDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👋 Welcome!.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
